name: Bug Report
description: Help us fix bugs by providing clear, detailed information.
title: "[Bug]: "
labels: [bug]
assignees: []

body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: What went wrong?
      placeholder: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: What did you do, and what happened?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error '...'
    validations:
      required: true

  - type: input
    attributes:
      label: Environment
      description: OS, browser, Go version, Docker version, etc.
      placeholder: "Ubuntu 22.04, Go 1.21, Docker 24.0.2"

  - type: textarea
    attributes:
      label: Additional context
      description: Any logs, screenshots, or error messages
