# Build stage
FROM golang:1.24-alpine AS builder

WORKDIR /app

RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -ldflags="-s -w" -o safesurf ./server/go/cmd/safesurf  # Smaller binary

# Final minimal image
FROM scratch

WORKDIR /app

COPY --from=builder /app/safesurf .
COPY --from=builder /app/internal/data ./internal/data

ENV PORT=8080

EXPOSE 8080

CMD ["./safesurf"]
